In [8]:
from push_task import *


Bad key savefig.frameon in file /home/gun/anaconda3/envs/py3_gpu/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 421 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file /home/gun/anaconda3/envs/py3_gpu/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 472 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file /home/gun/anaconda3/envs/py3_gpu/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 473 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr'

In [9]:
env = UR5Env(, camera_height=512, camera_width=512)

InstantSoup
Rusk
FlowerCup
bread
CoffeeBox
bread
CoffeeBox
InstantSoup
FlowerCup
FlowerCup
[ 0.19661471 -0.01272267  1.04861938] [-0.2583053   0.5995791  -0.23784725  0.71917444]
[0.07034325 0.29523093 1.02728985] [ 0.47538763 -0.17305121  0.80925983 -0.29859403]
[-0.17129763  0.02099996  1.02701573] [-0.09573163 -0.78859425 -0.10682642 -0.59794873]
[-0.01273428  0.06759356  1.04042275] [-0.03825763 -0.19734108 -0.49291983  0.8465358 ]
[0.15342554 0.14637582 1.01049147] [-0.44477928  0.02876761 -0.19030716  0.8747154 ]
[-0.01274831  0.22325497  1.02431197] [ 0.38700315  0.7634376  -0.5169448  -0.01263253]
[-0.08353204 -0.09489585  1.03792106] [ 0.3978768  -0.42636052  0.10313834  0.8057749 ]
[-0.01914713 -0.01391398  1.01995858] [-0.7954126   0.07218757  0.37565547 -0.47009653]
[0.07269467 0.21578094 1.03988556] [ 0.62458986  0.5193863  -0.52768004 -0.24835289]
[-0.1816769   0.28855608  1.04033899] [ 0.6282738   0.16566427 -0.6800766  -0.3395927 ]
Creating window glfw


In [12]:
dir(env.sim.model)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_actuator_id2name',
 '_actuator_name2id',
 '_body_id2name',
 '_body_name2id',
 '_camera_id2name',
 '_camera_name2id',
 '_geom_id2name',
 '_geom_name2id',
 '_joint_id2name',
 '_joint_name2id',
 '_light_id2name',
 '_light_name2id',
 '_mesh_id2name',
 '_mesh_name2id',
 '_sensor_id2name',
 '_sensor_name2id',
 '_site_id2name',
 '_site_name2id',
 '_tendon_id2name',
 '_tendon_name2id',
 '_userdata_id2name',
 '_userdata_name2id',
 'actuator_acc0',
 'actuator_biasprm',
 'actuator_biastype',
 'actuator_cranklength',
 'actuator_ctrllimited',
 'actuator_ctrlrange',
 'actuator_dynprm',
 'actuator_dyntype',
 'actuator_forcelimited',
 'actuato

In [29]:
dir(env.model.objects[0])

['__class__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'attrib',
 'clear',
 'extend',
 'find',
 'findall',
 'findtext',
 'get',
 'getchildren',
 'getiterator',
 'insert',
 'items',
 'iter',
 'iterfind',
 'itertext',
 'keys',
 'makeelement',
 'remove',
 'set',
 'tag',
 'tail',
 'text']

In [30]:
env.model.objects[0].set("rgba", "1 0 0 0")

In [ ]:
for i in range(100):
    env.sim.forward()
    action = 0.1 * np.random.random(3)
    frame = env.move_pos_diff(action, grasp=0.0)
    frame = env.move_pos_diff(-action, grasp=0.0)

In [1]:
import mujoco_py
from mujoco_py import MjSim, MjViewer
from base import MujocoXML

In [2]:
ur5_path = 'make_urdf/meshes_mujoco/ur5_robotiq.xml'
obj1_path = 'make_urdf/objects/dounut.xml'

In [3]:
ur5 = MujocoXML(ur5_path)
obj1 = MujocoXML(obj1_path)

In [4]:
ur5.merge(obj1)

In [5]:
mjpy_model = ur5.get_model(mode='mujoco_py')
sim = MjSim(mjpy_model)
viewer = MjViewer(sim)
sim.render(mode='window')

Creating window glfw


In [7]:
print(obj1)

In [6]:
obj1.set

AttributeError: 'MujocoXML' object has no attribute 'set'

In [6]:
for _ in range(10000):
    sim.step()
    viewer.render()

KeyboardInterrupt: 

In [ ]:
simm = MjSim(ur5)