In [1]:
from train_vae import *

In [5]:
for i, data in enumerate(data_loader):
    print(data[0].shape)
    print(data[0].type())
    
    print(data[1].shape)
    print(data[0].type())
    if i==5:
        break

torch.Size([50, 3, 96, 96])
torch.FloatTensor
torch.Size([50])
torch.FloatTensor
torch.Size([50, 3, 96, 96])
torch.FloatTensor
torch.Size([50])
torch.FloatTensor
torch.Size([50, 3, 96, 96])
torch.FloatTensor
torch.Size([50])
torch.FloatTensor
torch.Size([50, 3, 96, 96])
torch.FloatTensor
torch.Size([50])
torch.FloatTensor
torch.Size([50, 3, 96, 96])
torch.FloatTensor
torch.Size([50])
torch.FloatTensor
torch.Size([50, 3, 96, 96])
torch.FloatTensor
torch.Size([50])
torch.FloatTensor


In [2]:
from data_loader import *

In [3]:
x = load_urdata('data')

In [8]:
x = torch.tensor(x[0])

In [10]:
x.type()

'torch.ByteTensor'

In [13]:
(x/255).type()

'torch.FloatTensor'

In [4]:
x.shape

(2800, 50, 3, 96, 96)

In [15]:
np.random.random_integers(0, 49, 10).reshape([2, -1])

/home/gun/anaconda3/envs/py3_gpu/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 49 + 1) instead
  """Entry point for launching an IPython kernel.


array([[19, 22,  5, 35, 44],
       [ 4, 15, 42,  7, 20]])

In [21]:
idx = np.random.random_integers(0, 49, 10).reshape([2, -1])

/home/gun/anaconda3/envs/py3_gpu/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 49 + 1) instead
  """Entry point for launching an IPython kernel.


In [22]:
idx[0]

array([47, 22, 47, 13,  6])

In [23]:
idx[1]

array([42, 14,  9,  0,  8])

In [26]:
np.abs(idx[0]-idx[1])

array([ 5,  8, 38, 13,  2])

In [31]:
(x[0][idx[0][0]]==x[0][idx[0]][0]).all()

True

In [38]:
x1 = x[0][idx[0]]
x2 = x[0][idx[1]]

In [39]:
x1.shape

(5, 3, 96, 96)

In [41]:
y = np.concatenate([x1,x2]).reshape(2, 5, 3, 96, 96).transpose([1,0,2,3,4])

In [42]:
y.shape

(5, 2, 3, 96, 96)

In [43]:
x1.shape

(5, 3, 96, 96)

In [45]:
(x2[3]==y[3][1]).all()

True

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
Dataset(x)

In [55]:
np.array([np.arange(10)]*10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [6]:
np.random.randint(50, size=100)

array([20, 38, 36, 29, 31, 26, 10, 15, 20,  7, 49, 17, 14,  2, 47, 12, 15,
       22, 17, 45, 17, 30, 29, 30,  7, 45, 15, 36, 21, 27,  0, 38, 32,  4,
       30, 11, 23, 38, 38, 37, 18,  4, 13,  9,  3, 17, 45, 12, 37, 45, 38,
       25, 39, 11,  7, 32, 44,  8, 39,  9, 23,  5, 32, 14,  8, 18, 46, 22,
       20, 23, 35,  4, 31, 29, 44, 28, 35,  5,  2, 41, 17,  8, 12, 24, 11,
       11, 14, 42, 43, 39, 17, 11, 36,  8, 41, 26, 26, 32, 10, 47])

In [7]:
im = np.random.random([16, 5, 2, 3, 3])

In [9]:
m = np.zeros([16, 5])

In [10]:
idx = np.random.randint(5, size=32).reshape(2, 16)

In [11]:
idx

array([[1, 1, 2, 3, 2, 1, 1, 1, 3, 1, 4, 3, 2, 0, 3, 1],
       [4, 0, 1, 3, 4, 0, 4, 3, 2, 1, 2, 4, 1, 3, 4, 1]])

In [12]:
m[np.arange(16), idx[0]] = 1
m[np.arange(16), idx[1]] = 1

In [14]:
im[m.astype(bool)].shape

(29, 2, 3, 3)

In [17]:
m.sum()

29.0