In [1]:
!export DISPLAY=:1

In [2]:
from sdf_module import *

In [3]:
sdf = SDFModule()

NameError: name 'cfg_from_file' is not defined

In [1]:
import numpy as np

In [6]:
np.random.random([4, 4])

array([[0.87465263, 0.05063093, 0.55240866, 0.53477956],
       [0.73353931, 0.27930044, 0.24560154, 0.31385455],
       [0.22677773, 0.77063601, 0.85382876, 0.73178518],
       [0.6376409 , 0.30426465, 0.42438902, 0.57248278]])

In [57]:
x = np.random.random([4, 5])
y = np.random.random([3, 5])

In [58]:
x

array([[0.22528214, 0.31806226, 0.88344064, 0.92648594, 0.83566208],
       [0.3668644 , 0.7644503 , 0.04244904, 0.85577784, 0.32350456],
       [0.9425407 , 0.26291178, 0.38333796, 0.75014566, 0.06128139],
       [0.39494688, 0.29380051, 0.30749481, 0.67604863, 0.48976418]])

In [59]:
y

array([[0.52351866, 0.91358968, 0.8295233 , 0.16491657, 0.22462323],
       [0.17310878, 0.6104136 , 0.93115895, 0.85961329, 0.19762063],
       [0.58762701, 0.00232854, 0.08726474, 0.7288137 , 0.81258635]])

In [60]:
x.dot(y.T)

array([[1.48185439, 2.01733519, 1.56449895],
       [1.13946531, 1.36923429, 1.10764179],
       [1.18909557, 1.33754122, 1.18443932],
       [0.95175332, 1.21196304, 1.15028823]])

In [45]:
x.dot(y.T).argmax(1)

array([1, 0, 1])

In [63]:
xn = x / np.linalg.norm(x, axis=1).reshape(4, 1)
yn = y / np.linalg.norm(y, axis=1).reshape(3, 1)

In [64]:
xn.dot(yn.T)

array([[0.68603269, 0.89357979, 0.79795091],
       [0.66681712, 0.76665397, 0.7141124 ],
       [0.67188906, 0.72310934, 0.73731868],
       [0.68371166, 0.83301717, 0.91036777]])

In [65]:
xn.dot(yn.T).argmax(1)

array([1, 1, 2, 2])